version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    run_tests:
        docker:
            - image: circleci/python:3.7.4
    run_tests:
        steps:
          - checkout
          - python/load-cache
          - python/install-deps
          - python/save-cache
          
          -run
            name: install venv
            command: |
                sudo pip install pipenv
                pipenv install
          
          - run:
              name: install dependency
              command: |
                pip install -r requirements.txt
                
          - run:
              name: test
              command: |
                pipenv run src\test\test_cases.py test

              


    workflows:
      main:
        jobs:
          - build-and-test
